COND={
"()=>S.eta>=16":"Hai almeno 16 anni",
"()=>!!S.lavoro":"Hai un lavoro",
"()=>S.eta>=14":"Hai almeno 14 anni",
"()=>vivi(['Fratello']).length>0":"Hai fratelli o sorelle",
"()=>!['genitori','carcere','figlio'].includes(S.casa.tipo)":"Vivi in una casa tua o in affitto",
"()=>genitoriVivi()":"Almeno un genitore è vivo",
"()=>gr()!==3":"La malattia non è cronica",
"()=>gr()===3":"La malattia è cronica",
"()=>vivi(['Madre']).length>0":"Tua madre è viva",
"()=>iscritto()":"Stai studiando",
"()=>hobbySk()==='sport'":"Pratichi uno sport come attività",
"()=>S.hobby==='musica'":"Frequenti la scuola di musica",
"()=>S.abil.arte>=35":"Arte almeno 35",
"()=>S.scuola.voto>=60":"Media scolastica almeno 60/100",
"()=>S.scuola.voto<60":"Media scolastica sotto 60/100",
"()=>vivi(['Nonno']).some(p=>p.sesso==='M')":"Hai un nonno vivo",
"()=>!S.dip.fumo":"Non fumi",
"()=>S.scuola.stato==='superiori'":"Frequenti le superiori",
"()=>S.scuola.stato==='superiori'&&S.scuola.anni<=1":"Sei all'ultimo anno delle superiori",
"()=>S.istr.liv>=2":"Hai il diploma",
"()=>['universita','magistrale'].includes(S.scuola.stato)":"Sei all'università",
"()=>S.fatti.fuorisede||(S.casa.tipo==='affitto'&&S.casa.n==='Stanza in condivisione')":"Vivi fuori sede o in una stanza in condivisione",
"()=>S.patente&&haAuto()":"Hai la patente e un'auto",
"()=>!lavora()":"Non hai un lavoro a tempo pieno",
"()=>S.soldi>=1000":"Hai almeno 1.000 €",
"()=>S.soldi>=1500":"Hai almeno 1.500 €",
"()=>S.soldi>200":"Hai più di 200 €",
"()=>S.casa.tipo!=='genitori'":"Non vivi con i genitori",
"()=>S.veicoli.length>0":"Possiedi un veicolo",
"()=>S.aspetto>=65":"Aspetto almeno 65",
"()=>S.abil.tech>=30":"Tecnologia almeno 30",
"()=>['affitto','proprieta'].includes(S.casa.tipo)&&!S.fatti.allarme":"Vivi in una casa tua o in affitto, senza allarme",
"()=>!!casaMia()":"Vivi in una casa di tua proprietà",
"()=>vivi(['Amico']).length>0":"Hai almeno un amico",
"()=>S.casa.tipo==='genitori'&&genitoriVivi()":"Vivi ancora con i genitori",
"()=>single()&&S.carcere===0":"Sei single e libero/a",
"()=>lavora()":"Hai un lavoro a tempo pieno",
"()=>lavora()&&S.intelligenza>45":"Hai un lavoro a tempo pieno e Intelletto sopra 45",
"()=>lavora()&&!JOB[S.lavoro.id].conc":"Hai un lavoro nel privato",
"()=>!S.lavoro&&S.carcere===0":"Sei disoccupato/a e libero/a",
"()=>!!S.impresa":"Hai un'attività in proprio",
"()=>lavora()&&S.lavoro.perf>=75":"Rendimento al lavoro almeno 75%",
"()=>S.animali.length<3":"Hai meno di 3 animali",
"()=>S.animali.length>0":"Hai almeno un animale",
"()=>haAuto()":"Possiedi un'auto",
"()=>S.soldi>=800":"Hai almeno 800 €",
"()=>S.lavoro&&S.lavoro.liv>=2":"Sei almeno al terzo livello di carriera",
"()=>!S.lavoro":"Non lavori",
"d=>d.p&&['Partner','Coniuge'].includes(d.p.ruolo)":"La persona è ancora il tuo partner",
"()=>S.classe==='umile'&&S.soldi>=800":"Famiglia di condizioni modeste e almeno 800 €",
"()=>S.soldi>=2000":"Hai almeno 2.000 €",
"()=>S.soldi>=500":"Hai almeno 500 €",
"()=>S.soldi>=10000":"Hai almeno 10.000 €",
"()=>single()":"Sei single",
"()=>S.soldi>=20000":"Hai almeno 20.000 €",
"()=>S.casa.tipo!=='figlio'":"Non vivi già da un figlio",
}
PC={
"p=>p.eta>=65":"la persona ha almeno 65 anni",
"p=>p.sesso==='F'":"è tua nonna",
"p=>p.eta>=18":"la persona è maggiorenne",
"p=>p.eta>=24&&!p.sposato":"ha almeno 24 anni e non è sposata",
"p=>p.sposato&&p.eta>=25&&p.eta<=45&&!p.figli":"è sposata, 25–45 anni, senza figli",
"p=>p.tr===TR.GELOSO||p.rapporto<50":"è gelosa oppure il rapporto è sotto 50%",
"p=>!p.conv&&p.rapporto>=55":"non convivete e il rapporto è almeno 55%",
"p=>p.rapporto>=62":"rapporto almeno 62%",
"p=>p.conv&&p.rapporto>=55":"convivete e il rapporto è almeno 55%",
"p=>p.rapporto<45":"rapporto sotto 45%",
"p=>p.conv":"convivete",
"p=>p.eta>=7&&p.eta<=18":"il figlio ha 7–18 anni",
"p=>p.eta>=9&&p.eta<=14":"il figlio ha 9–14 anni",
"p=>p.eta>=8&&p.eta<=15":"il figlio ha 8–15 anni",
"p=>p.eta>=14&&p.eta<=17":"il figlio ha 14–17 anni",
"p=>p.eta>=18&&p.eta<=20&&p.studio==='diploma'&&!p.uni":"il figlio ha 18–20 anni ed è diplomato",
"p=>p.eta>=26&&p.eta<=45":"il figlio ha 26–45 anni",
"p=>p.eta>=24&&p.eta<=45&&p.sposato":"il figlio ha 24–45 anni ed è sposato",
"p=>p.eta>=30&&p.rapporto>=50":"il figlio ha almeno 30 anni e il rapporto è almeno 50%",
}
PF={
"()=>(S.fatti.ultimoVoto||90)>=105?.75:(S.fatti.ultimoVoto||90)>=100?.4:.1":"75% con laurea ≥105/110 · 40% con ≥100 · 10% sotto",
"()=>.25+S.abil.sport/180":"25% + Sport ÷ 180",
"()=>S.abil.musica/140":"Musica ÷ 140",
"()=>.4+S.aspetto/250+S.abil.arte/200":"40% + Aspetto ÷ 250 + Arte ÷ 200",
"()=>S.intelligenza/120":"Intelletto ÷ 120",
"()=>S.classe==='umile'?.35:.7":"35% se famiglia modesta, altrimenti 70%",
"()=>.3+S.abil.sport/150":"30% + Sport ÷ 150",
"()=>.3+S.abil.musica/130":"30% + Musica ÷ 130",
"()=>S.abil.arte/130":"Arte ÷ 130",
"()=>S.intelligenza/130":"Intelletto ÷ 130",
"()=>.25+S.aspetto/250+S.karma/250":"25% + Aspetto ÷ 250 + Karma ÷ 250",
"()=>({umile:.15,media:.45,agiata:.85})[S.classe]":"15% famiglia modesta · 45% media · 85% benestante",
"()=>S.intelligenza/110":"Intelletto ÷ 110",
"()=>.2+S.abil.tech/150":"20% + Tecnologia ÷ 150",
"()=>S.abil.tech/180+S.intelligenza/400":"Tecnologia ÷ 180 + Intelletto ÷ 400",
"()=>S.salute/110":"Salute ÷ 110",
"d=>.3+d.p.rapporto/200":"30% + Rapporto ÷ 200",
"d=>d.p.rapporto/160":"Rapporto ÷ 160",
"()=>.3+S.abil.cucina/120":"30% + Cucina ÷ 120",
}
COND.update({
"()=>S.prop.length||S.veicoli.length||valoreBorsa()||S.azienda":"Possiedi case, veicoli, azioni o un'azienda",
"()=>genitoriVivi()&&S.classe!=='umile'":"I genitori sono vivi e la famiglia non è modesta",
"()=>!!S.azienda":"Hai un'azienda",
"()=>S.mondo.boom>0&&lavora()":"C'è un boom economico e lavori a tempo pieno",
"()=>['affitto','proprieta'].includes(S.casa.tipo)":"Vivi in affitto o in una casa tua",
"d=>d.p&&d.p.ruolo==='Partner'":"State ancora insieme",
"()=>S.soldi>=P(5000)":"Hai almeno 5.000 € (rivalutati)",
"()=>S.soldi<-2000":"Sei in rosso di oltre 2.000 €",
"()=>!!casaMia()||S.casa.tipo==='genitori'":"Vivi in una casa tua o dai genitori",
"()=>S.animali.some(a=>a.t==='Gatto')":"Hai un gatto",
"()=>inReg('Lombardia','Piemonte','Emilia-Romagna','Veneto')()&&S.patente&&haAuto()":"Vivi in Pianura Padana (Lombardia, Piemonte, Emilia-Romagna o Veneto) e guidi",
"()=>inCitta('Roma')()&&haAuto()":"Vivi a Roma e hai l'auto",
"()=>inZona('Sud','Isole')()&&!S.lavoro&&S.carcere===0&&S.scuola.stato==='finita'":"Vivi al Sud o nelle Isole, hai finito gli studi e non lavori",
"()=>S.abil.lingue>=30":"Lingue almeno 30",
"()=>conAz()&&S.azienda.dip>0":"Hai un'azienda con dipendenti",
"()=>conAz()&&valoreAzienda(S.azienda)>20000":"La tua azienda vale più di 20.000 €",
"()=>conAz()&&['agenzia','startup','edile','shop'].includes(S.azienda.id)":"Hai un'agenzia, una startup, un'impresa edile o un negozio online",
"()=>social()&&S.social.follower>800":"Hai più di 800 follower",
"()=>S.eta>=18":"Sei maggiorenne",
"()=>social()&&S.social.follower>=5000":"Hai almeno 5.000 follower",
"()=>social()&&single()&&S.social.follower>200":"Sei single con più di 200 follower",
"()=>S.social.attivo":"Hai un profilo social",
"()=>social()&&S.fama>=10":"Hai un profilo social e fama almeno 10",
"()=>S.fama>=30":"Fama almeno 30","()=>S.fama>=35":"Fama almeno 35","()=>S.fama>=40":"Fama almeno 40","()=>S.fama>=20":"Fama almeno 20",
"()=>S.fama>=45&&S.lavoro&&['att','mus'].includes(S.lavoro.id)":"Fama almeno 45 e lavori come attore o musicista",
"()=>S.lavoro&&S.lavoro.id==='mus'&&S.lavoro.liv>=1":"Sei musicista almeno al secondo grado",
"()=>iscritto()&&!vivi(['Nemico']).length":"Vai a scuola e non hai nemici",
"()=>lavora()&&!vivi(['Nemico']).length":"Lavori e non hai nemici",
"()=>S.soldi>=P(3000)":"Hai almeno 3.000 € (rivalutati)",
"()=>!casaMia()":"Non hai una casa tua",
"()=>S.soldi>=P(1000)":"Hai almeno 1.000 € (rivalutati)",
"()=>!!S.fatti.separati&&!vivi(['Patrigno']).length":"I tuoi genitori si sono separati",
"()=>S.crim.exp>=3&&!S.crim.clan&&S.carcere===0":"Esperienza criminale almeno 3, non sei in un clan",
"()=>!!S.crim.clan&&S.carcere===0":"Sei in un clan e sei libero/a",
"()=>S.crim.exp>=2":"Esperienza criminale almeno 2",
"()=>S.crim.colpi>=3&&!S.crim.clan&&S.carcere===0":"Hai fatto almeno 3 colpi e non sei in un clan",
"()=>S.galera&&S.galera.banda":"In carcere fai parte di una banda",
"()=>conAz()||S.prop.some(p=>p.affittata)||(S.lavoro&&JOB[S.lavoro.id].var)":"Hai un'azienda, case affittate o guadagni variabili",
"()=>chance(.45)":"Succede nel 45% dei casi",
})
PF.update({
"()=>.3+S.abil.musica/120":"30% + Musica ÷ 120","()=>.6+S.abil.sport/250":"60% + Sport ÷ 250","()=>S.salute/100":"Salute ÷ 100","()=>.4+S.aspetto/250":"40% + Aspetto ÷ 250",
"()=>({base:.45,buona:.75,top:.9})[S.azienda.qualita]":"45% qualità base · 75% buona · 90% eccellente",
"()=>S.azienda.rep/110":"Reputazione ÷ 110","()=>S.fatti.addettoStampa?.85:.5":"85% con l'addetto stampa, altrimenti 50%",
"()=>.25+S.abil.arte/400+S.abil.musica/400":"25% + Arte ÷ 400 + Musica ÷ 400","()=>S.abil.musica/150":"Musica ÷ 150",
})
PC.update({"p=>(p.rancore||50)<45":"il rancore è sotto 45%","p=>p.eta>=60":"ha almeno 60 anni","p=>p.eta>=20":"ha almeno 20 anni"})
# infanzia, adolescenza, età adulta (d4, d5, d6)
COND.update({
"()=>!!nonnoV()":"Hai un nonno o una nonna in vita",
"()=>vivi(['Fratello']).some(f=>f.eta<S.eta)":"Hai un fratello o una sorella più piccoli",
"()=>vivi(['Fratello']).some(f=>f.eta>S.eta)":"Hai un fratello o una sorella più grandi",
"()=>vivi(['Nonno']).some(n=>n.sesso==='M')":"Hai un nonno vivo",
"()=>vivi(['Nonno']).length>0":"Hai un nonno o una nonna in vita",
"()=>famG().length>=2":"Vivi con entrambi i genitori",
"()=>famG().length>0":"Hai almeno un genitore in vita",
"()=>S.casa.tipo==='genitori'":"Vivi con i genitori",
"()=>S.classe!=='agiata'&&famG().length>0":"La tua famiglia non è agiata",
"()=>iscritto()&&S.scuola.voto<45":"Vai a scuola e la media è sotto 45/100",
"()=>S.fatti.fuorisede||S.casa.tipo==='affitto'":"Vivi fuori sede o in affitto",
"()=>S.bis.stress>55||S.felicita<45":"Stress sopra 55 o felicità sotto 45",
"()=>lavora()||iscritto()":"Lavori o studi",
"()=>!['genitori','carcere'].includes(S.casa.tipo)":"Vivi in una casa tua o in affitto",
"()=>!S.lavoro&&S.pensione>0":"Sei in pensione",
"()=>S.soldi>=P(3500)&&S.salute>45":"Hai almeno 3.500 € (rivalutati) e salute sopra 45",
"()=>!!vedovo()&&single()":"Sei vedovo/a e non hai un nuovo partner",
"()=>!!fratV()":"Hai un fratello o una sorella",
"()=>S.classe==='umile'":"La tua famiglia è umile",
"()=>S.soldi>=P(600)":"Hai almeno 600 € (rivalutati)",
})
PC.update({"p=>p.rapporto>=40":"il rapporto è almeno 40","p=>p.eta>=9&&p.eta<=15":"ha tra 9 e 15 anni","p=>p.rapporto<35&&p.eta>=18":"è adulto/a e il rapporto è sotto 35",
"p=>p.eta>=19&&p.eta<=35":"ha tra 19 e 35 anni","p=>vivi(['Nipote']).some(n=>n.gen===p.id&&n.eta<11)":"ha figli sotto gli 11 anni"})
PF.update({"()=>.45+pz('E')*.25":"45%, di più se sei estroverso/a","()=>.4+pz('C')*.4":"40%, di più se sei coscienzioso/a","()=>.4+pz('C')*.3":"40%, di più se sei coscienzioso/a",
"()=>.45+pz('C')*.35":"45%, di più se sei coscienzioso/a","()=>.5+pz('O')*.3":"50%, di più se sei aperto/a"})
PC.update({"p=>p.rapporto>=70&&amorePossibile(p)&&ricambia(p)":"è un amico o un'amica con rapporto almeno 70, ti piace, ricambia e ha un'età compatibile"})
# ottobre 2026: famiglia, regole italiane, storia vera
COND.update({"()=>!!S.orient&&S.orient!=='etero'":"Non sei eterosessuale (orientamento deciso alla nascita)","()=>!S.provano&&!S.gravidanza":"Non state già provando ad avere un figlio e non aspettate un bambino",
"()=>!inSeparazione()":"Non sei in attesa di un divorzio","()=>S.anno>=2010":"Dal 2010 in poi","()=>S.eta<12":"Hai meno di 12 anni","()=>S.eta<16":"Hai meno di 16 anni","()=>S.eta>=12":"Hai almeno 12 anni",
"()=>S.eta>=14":"Hai almeno 14 anni","()=>S.social.attivo":"Hai un profilo social","()=>gr()===2":"La malattia si può curare","()=>gr()===4&&!tum()":"È una malattia grave che non guarisce (cuore, fegato)",
"()=>{const x=m();return !!(x&&x.tum)}":"È un tumore","d=>!!(d&&d.p&&d.p.sesso===S.sesso)":"Siete una coppia dello stesso sesso (unione civile)","d=>!unioneCivile(d)":"Siete una coppia di sesso diverso",
"d=>S.citta===d.citta||S.casa.tipo==='genitori'":"Vivi nella stessa città della casa (o ci vivevi con i tuoi)","d=>d.n>1":"Hai fratelli o sorelle"})
PC.update({"p=>(p.sposato||['coppia','sposato'].includes(p.coppia))&&!coppiaStessoSesso(p)&&p.eta>=25&&p.eta<=45&&!p.figli":"ha un compagno o è sposata (sesso diverso), 25–45 anni, senza figli",
"p=>p.conv&&p.rapporto>=55&&!!coppiaFertile(p)":"convivete, siete di sesso diverso e il rapporto è almeno 55%",
"p=>p.eta>=24&&p.eta<=45&&(p.sposato||['coppia','sposato'].includes(p.coppia))&&!coppiaStessoSesso(p)":"il figlio ha 24–45 anni e ha un compagno o è sposato (sesso diverso)"})

# Fase 1 (ottobre 2026): ritmo, infanzia, adolescenza, vita adulta, catene
COND.update({
"()=>S.soldi>=P(1500)":"Hai almeno 1.500 € (rivalutati)","()=>S.soldi>P(200)":"Hai più di 200 € (rivalutati)","()=>S.soldi>=P(800)":"Hai almeno 800 € (rivalutati)",
"()=>S.classe==='umile'&&S.soldi>=P(800)":"Famiglia modesta e almeno 800 € (rivalutati)","()=>S.soldi>=P(2000)":"Hai almeno 2.000 € (rivalutati)",
"()=>S.soldi>=P(500)":"Hai almeno 500 € (rivalutati)","()=>S.soldi>=P(10000)":"Hai almeno 10.000 € (rivalutati)","()=>S.soldi>=P(20000)":"Hai almeno 20.000 € (rivalutati)",
"()=>S.soldi<-P(2000)":"Sei in rosso di oltre 2.000 € (rivalutati)","()=>S.soldi>=P(60000)":"Hai almeno 60.000 € (rivalutati)",
"()=>luogo().zona!=='Isole'":"Non vivi nelle Isole (lì nevica di rado)","()=>haAnimale()":"Hai un animale","()=>!haAnimale('Cane')":"Non hai un cane",
"()=>S.classe!=='umile'":"La famiglia non è di condizioni modeste","()=>S.sesso==='F'":"Sei una ragazza","()=>S.sesso==='M'":"Sei un ragazzo",
"()=>scuolaDi()==='medie'":"Frequenti le medie","()=>scuolaDi()==='superiori'":"Frequenti le superiori","()=>scuolaDi()==='superiori'&&S.scuola.voto<55":"Frequenti le superiori con una media sotto 55/100",
"()=>S.anno>=2013":"Dal 2013 (i gruppi di classe sul telefono)","()=>S.anno>=2011":"Dal 2011 (i social con i like)","()=>S.anno>=2008":"Dal 2008 (i social)","()=>S.anno>=2005":"Dal 2005",
"()=>vivi(['Fratello']).some(f=>f.eta<18)":"Hai un fratello o una sorella minorenne","()=>S.anno>=2019&&iscritto()":"Dal 2019 (gli scioperi per il clima) e vai a scuola",
"()=>S.anno>=2016&&scuolaDi()==='superiori'":"Dal 2016 (l'alternanza scuola-lavoro) e frequenti le superiori","()=>S.veicoli.some(v=>/Scooter/.test(v.n))":"Hai uno scooter",
"()=>S.scuola.voto>=65":"Media scolastica almeno 65/100","()=>rOre('sport')>=3||S.abil.sport>=50":"Fai almeno 3 ore di sport a settimana o Sport almeno 50",
"()=>!!partnerAttuale()":"Hai un partner","()=>S.anno>=2023&&iscritto()":"Dal 2023 (l'intelligenza artificiale) e vai a scuola",
"()=>!!mutuoMio()&&((S.anno>=2022&&S.anno<=2023)||(S.anno>ANNO_OGGI&&S.mondo.crisi))":"Hai un mutuo e i tassi salgono (2022–2023, o una crisi dopo il 2026)",
"()=>S.casa.tipo==='proprieta'":"Vivi in una casa di tua proprietà","()=>S.anno===2022&&inCasaMia()":"Nel 2022 (il caro energia), in una casa tua o in affitto",
"()=>figliTra(0,13).length>0&&vivi(['Madre','Padre']).some(p=>p.eta>=75)":"Hai figli sotto i 14 anni e un genitore di almeno 75",
"()=>!!S.lavoro&&!JOB[S.lavoro.id].pt":"Hai un lavoro vero (non un lavoretto)","()=>!!S.lavoro&&S.anno>=2015":"Lavori, dal 2015 (i gruppi di lavoro sul telefono)",
"()=>S.bis.stress>=50":"Stress almeno 50","()=>S.bis.forma<45":"Forma sotto 45","()=>!!S.lavoro&&soddLavoro()<50":"Lavori, ma il lavoro ti soddisfa poco",
"()=>!!S.lavoro&&S.bis.stress>=45":"Lavori e lo stress è almeno 45","()=>!!S.lavoro&&!isPiva(S.lavoro)":"Sei dipendente",
"()=>{const p=partnerAttuale();return !!(p&&p.ruolo==='Coniuge'&&p.nozze!==undefined&&S.t-p.nozze>=96)}":"Sei sposat* da almeno 8 anni",
"()=>figliTra(0,6).length>0&&vivi(['Amico']).some(a=>!a.figliN)":"Hai figli piccoli e amici senza figli",
"()=>!!S.lavoro&&!JOB[S.lavoro.id].pt&&!isPiva(S.lavoro)&&!(S.lavoro.contratto&&S.lavoro.contratto.t==='carica')":"Sei dipendente (non un lavoretto, non una carica elettiva)",
"d=>d.p&&!d.p.fuori":"Il figlio vive ancora con te","()=>S.animali.some(a=>a.nome==='Briciola')":"Briciola vive con te","()=>luogo().p>=30000":"Vivi in una città di almeno 30.000 abitanti",
"()=>pz('O')>-.2":"Non sei troppo abitudinari*","()=>S.relazioni.some(p=>p.ruolo==='Nonno'&&!p.vivo)":"Un nonno è morto","d=>d.p&&d.p.eta<20":"Il figlio ha meno di 20 anni",
"()=>S.prop.some(p=>p.rudere)":"Hai il casale da sistemare","()=>rOre('sport')>=3":"Fai almeno 3 ore di sport a settimana","()=>rOre('sport')>=2":"Fai almeno 2 ore di sport a settimana",
"()=>S.casa.tipo==='genitori'&&S.classe!=='umile'":"Vivi con i genitori e la famiglia non è modesta",
"()=>['universita','magistrale'].includes(S.scuola.stato)&&(S.scuola.anni||9)<=1":"Sei all'ultimo anno di università","()=>inCasaMia()":"Vivi in una casa tua o in affitto",
"()=>(S.fatti.viaggi||0)<4":"Hai fatto meno di 4 viaggi","()=>genitoriVivi()||vivi(['Suocero']).length>0":"Ci sono i nonni","()=>vivi(['Nipote']).some(n=>n.eta<14)":"Hai nipoti sotto i 14 anni",
"()=>genitoriVivi()||vivi(['Fratello']).length>0":"Hai genitori o fratelli","()=>vivi(['Zio','Cugino','Nonno','Fratello']).length>0":"Hai parenti",
"()=>S.anno<2008":"Prima del 2008","()=>vivi(['Padre']).length>0":"Tuo padre è vivo","()=>vivi(['Zio']).length>0":"Hai uno zio o una zia",
"()=>vivi(['Fratello','Zio','Cugino']).length>0":"Hai fratelli, zii o cugini","()=>luogo().p>=100000":"Vivi in una città di almeno 100.000 abitanti",
"()=>famG().length>0":"Hai almeno un genitore","()=>!!nonnoV()":"Hai un nonno o una nonna",
})
PC.update({
"p=>p.eta===13&&!p.fuori&&!p.conEx":"il figlio ha 13 anni e vive con te","p=>p.eta>=14&&p.eta<=19&&!p.fuori&&!p.conEx":"il figlio ha 14–19 anni e vive con te",
"p=>p.eta>=15&&p.eta<=28&&!p.coming&&orientNpc(p)!=='etero'":"il figlio ha 15–28 anni e non è eterosessuale","p=>p.eta>=12&&p.eta<=15&&!p.fuori&&!p.conEx":"il figlio ha 12–15 anni e vive con te",
"p=>p.eta>=16&&p.eta<=22&&!p.fuori&&!p.conEx":"il figlio ha 16–22 anni e vive con te","p=>p.eta>=22&&p.eta<=32&&!p.lontano":"il figlio ha 22–32 anni e vive vicino",
"p=>p.eta>=24&&p.eta<=38&&p.fuori":"il figlio ha 24–38 anni e vive da solo","p=>p.eta===18&&!p.fuori&&!p.conEx":"il figlio ha 18 anni e vive con te",
"p=>p.eta>=75":"il genitore ha almeno 75 anni","p=>p.eta>=80":"il genitore ha almeno 80 anni","p=>p.eta>=78&&p.malattia!=='Demenza'":"il genitore ha almeno 78 anni (senza demenza)",
"p=>p.eta>=78&&p.coppia==='vedovo'":"il genitore ha almeno 78 anni ed è vedovo","p=>p.eta===80":"il genitore compie 80 anni",
"p=>p.eta>=28&&p.eta<=42&&p.fuori&&!p.lontano":"il figlio ha 28–42 anni e vive da solo, vicino","p=>p.eta>=14&&p.eta<=17&&!p.fuori&&!p.conEx":"il figlio ha 14–17 anni e vive con te",
"p=>p.rapporto>=55&&!p.lontano":"rapporto almeno 55% e vive vicino",
})
PF.update({
"()=>.45+S.intelligenza/250":"45% + Intelletto ÷ 250","()=>.4+S.abil.musica/150":"40% + Musica ÷ 150","()=>.5+pz('A')*.2":"50%, di più se sei gentile",
"()=>({umile:.45,media:.6,agiata:.7})[S.classe]":"45% famiglia modesta · 60% media · 70% benestante","()=>.35+pz('C')*.15":"35%, di più se sei costante",
"()=>.45+pz('C')*.2":"45%, di più se sei costante","()=>.55+S.abil.musica/200":"55% + Musica ÷ 200","()=>.55+pz('E')*.15+S.intelligenza/400":"55% + Intelletto ÷ 400, di più se sei estroverso/a",
"()=>.6+pz('E')*.2":"60%, di più se sei estroverso/a","()=>.75+pz('C')*.15":"75%, di più se sei costante","()=>.6+pz('C')*.2":"60%, di più se sei costante",
"()=>({umile:.5,media:.65,agiata:.75})[S.classe]":"50% famiglia modesta · 65% media · 75% benestante",
"d=>.45+(d.p?d.p.rapporto:50)/250+(d.x==='aiuto'||d.x==='sport'?.15:0)":"45% + Rapporto ÷ 250, +15% con psicologo o sport",
"d=>d.x==='bravo'?.85:d.x==='pigro'?.5:.6":"85% con una buona riabilitazione · 50% se svogliata · 60% se ti sei abbattut*",
"d=>d.x==='prot'?.65+pz('E')*.15:.85":"65% da protagonista (di più se sei estroverso/a) · 85% con la parte piccola",
"d=>d.x==='avvocato'?.9:.7":"90% con l'avvocato · 70% con la sola denuncia","d=>d.x==='cura'?.8:d.x==='vicino'?.7:.5":"80% con lo psicologo · 70% standogli vicino · 50% da solo",
})

# Fase 2 (ottobre 2026): persone vere
PC.update({
"p=>figlioCasa(9,14)(p)&&S.anno>=2010":"il figlio ha 9–14 anni e vive con te (dal 2010: i telefoni)",
"p=>figlioCasa(4,12)(p)&&vivi(['Figlio']).filter(figlioCasa(3,14)).length>=2":"il figlio ha 4–12 anni e ha un fratello o una sorella piccoli in casa",
"p=>p.conv&&p.pers&&Math.abs(p.pers.C-S.pers.C)>=25":"convivete e siete molto diversi su ordine e spese",
"p=>p.nozze!==undefined&&S.t-p.nozze>=240":"siete sposati da almeno 20 anni",
"p=>p.conv":"convivete",
})
# Fase 3 (Italia vera): epoche, territorio, mutui, sanità
COND.update({
"()=>!!mutuoVar()&&!!S.fatti.rataSu&&S.t-S.fatti.rataSu.t<=12":"Hai un mutuo a tasso variabile e quest'anno la rata è salita di più del 10%",
"()=>!!S.fatti.emigrato&&!S.fatti.ritornato":"Sei partito/a dal Sud per il Centro-Nord o l'estero e non sei ancora tornato/a",
"()=>S.anno>=1972":"Dal 1972 (legge sull'obiezione di coscienza)",
"()=>S.anno!==2020&&!!S.lavoro":"Hai ancora il lavoro e non è il 2020 (nel 2020 i licenziamenti erano bloccati)",
"()=>S.anno>=2020&&!!S.lavoro&&REMOTO.includes(S.lavoro.id)":"Dal 2020, con un lavoro che si può fare da remoto (impiegato, programmatore, grafico…)",
"()=>S.anno>=1999":"Dal 1999 (visite in intramoenia)",
"()=>S.anno>=1980&&['Centro','Sud','Isole'].includes(zonaMia())":"Dal 1980, se vivi al Centro, al Sud o nelle Isole",
})
PC.update({"p=>p.rapporto>=62&&(p.sesso!==S.sesso||unioneCivilePossibile())":"il rapporto è almeno 62 e, se è dello stesso sesso, c'è già l'unione civile (da giugno 2016)"})
